// In-memory course repository
const { defaultImageBase64 } = require('../utils/defaultImage');

const coursesData = {
  courses: [
    // Programming
    {
      id: 1,
      title: "React Fundamentals",
      instructor: "John Doe",
      lessons: 12,
      duration: "4h 30m",
      students: 245,
      rating: 4.8,
      price: 49.99,
      category: "Programming",
      image: defaultImageBase64
    },
    {
      id: 2,
      title: "UI/UX Design Basics",
      instructor: "Jane Smith",
      lessons: 8,
      duration: "3h 15m",
      students: 187,
      rating: 4.6,
      price: 39.99,
      category: "Design",
      image: defaultImageBase64
    },
    {
      id: 3,
      title: "Digital Marketing 101",
      instructor: "Sarah Johnson",
      lessons: 10,
      duration: "3h 0m",
      students: 320,
      rating: 4.7,
      price: 59.99,
      category: "Marketing",
      image: defaultImageBase64
    },
    {
      id: 4,
      title: "SEO Strategies for Beginners",
      instructor: "Mike Brown",
      lessons: 8,
      duration: "2h 30m",
      students: 150,
      rating: 4.5,
      price: 39.99,
      category: "Marketing",
      image: defaultImageBase64
    },
    {
      id: 5,
      title: "Social Media Advertising",
      instructor: "Emily Davis",
      lessons: 12,
      duration: "4h 15m",
      students: 280,
      rating: 4.8,
      price: 69.99,
      category: "Marketing",
      image: defaultImageBase64
    },
    {
      id: 6,
      title: "Content Marketing Mastery",
      instructor: "Alex Carter",
      lessons: 15,
      duration: "5h 0m",
      students: 200,
      rating: 4.6,
      price: 79.99,
      category: "Marketing",
      image: defaultImageBase64
    },
    {
      id: 7,
      title: "Email Marketing Essentials",
      instructor: "Laura Wilson",
      lessons: 9,
      duration: "2h 45m",
      students: 180,
      rating: 4.4,
      price: 49.99,
      category: "Marketing",
      image: defaultImageBase64
    },
    {
      id: 8,
      title: "Introduction to Data Science",
      instructor: "Dr. Robert Lee",
      lessons: 14,
      duration: "5h 30m",
      students: 400,
      rating: 4.9,
      price: 89.99,
      category: "Data Science",
      image: defaultImageBase64
    },
    {
      id: 9,
      title: "Python for Data Analysis",
      instructor: "Anna Kim",
      lessons: 10,
      duration: "3h 45m",
      students: 350,
      rating: 4.7,
      price: 59.99,
      category: "Data Science",
      image: defaultImageBase64
    },
    {
      id: 10,
      title: "Machine Learning Basics",
      instructor: "James Patel",
      lessons: 12,
      duration: "4h 0m",
      students: 300,
      rating: 4.8,
      price: 79.99,
      category: "Data Science",
      image: defaultImageBase64
    },
    {
      id: 11,
      title: "Data Visualization with Tableau",
      instructor: "Sophie Nguyen",
      lessons: 8,
      duration: "2h 30m",
      students: 220,
      rating: 4.6,
      price: 49.99,
      category: "Data Science",
      image: defaultImageBase64
    },
    {
      id: 12,
      title: "Statistics for Data Science",
      instructor: "Dr. Maria Gonzalez",
      lessons: 15,
      duration: "6h 0m",
      students: 250,
      rating: 4.7,
      price: 99.99,
      category: "Data Science",
      image: defaultImageBase64
    },
    {
      id: 13,
      title: "Photography for Beginners",
      instructor: "Chris Evans",
      lessons: 10,
      duration: "3h 0m",
      students: 180,
      rating: 4.5,
      price: 39.99,
      category: "Photography",
      image: defaultImageBase64
    },
    {
      id: 14,
      title: "Mastering Portrait Photography",
      instructor: "Lisa Thompson",
      lessons: 12,
      duration: "4h 15m",
      students: 200,
      rating: 4.7,
      price: 59.99,
      category: "Photography",
      image: defaultImageBase64
    },
    {
      id: 15,
      title: "Landscape Photography Techniques",
      instructor: "Mark Harris",
      lessons: 8,
      duration: "2h 45m",
      students: 150,
      rating: 4.6,
      price: 49.99,
      category: "Photography",
      image: defaultImageBase64
    },
    {
      id: 16,
      title: "Photo Editing with Lightroom",
      instructor: "Emma Clark",
      lessons: 9,
      duration: "3h 30m",
      students: 170,
      rating: 4.8,
      price: 59.99,
      category: "Photography",
      image: defaultImageBase64
    },
    {
      id: 17,
      title: "Street Photography Essentials",
      instructor: "David Miller",
      lessons: 7,
      duration: "2h 0m",
      students: 120,
      rating: 4.4,
      price: 29.99,
      category: "Photography",
      image: defaultImageBase64
    },
    {
      id: 18,
      title: "Yoga for Beginners",
      instructor: "Rachel Green",
      lessons: 10,
      duration: "3h 0m",
      students: 250,
      rating: 4.6,
      price: 39.99,
      category: "Health & Fitness",
      image: defaultImageBase64
    },
    {
      id: 19,
      title: "Strength Training Fundamentals",
      instructor: "Tom Wilson",
      lessons: 12,
      duration: "4h 0m",
      students: 200,
      rating: 4.7,
      price: 49.99,
      category: "Health & Fitness",
      image: defaultImageBase64
    },
    {
      id: 20,
      title: "Nutrition and Meal Planning",
      instructor: "Dr. Linda Hayes",
      lessons: 8,
      duration: "2h 30m",
      students: 180,
      rating: 4.5,
      price: 39.99,
      category: "Health & Fitness",
      image: defaultImageBase64
    },
    {
      id: 21,
      title: "HIIT Workouts for Fat Loss",
      instructor: "Jake Miller",
      lessons: 10,
      duration: "3h 15m",
      students: 220,
      rating: 4.8,
      price: 59.99,
      category: "Health & Fitness",
      image: defaultImageBase64
    },
    {
      id: 22,
      title: "Mindfulness and Meditation",
      instructor: "Sophie Adams",
      lessons: 7,
      duration: "2h 0m",
      students: 150,
      rating: 4.6,
      price: 29.99,
      category: "Health & Fitness",
      image: defaultImageBase64
    },
    {
      id: 23,
      title: "Guitar for Beginners",
      instructor: "Ben Taylor",
      lessons: 10,
      duration: "3h 0m",
      students: 200,
      rating: 4.5,
      price: 39.99,
      category: "Music",
      image: defaultImageBase64
    },
    {
      id: 24,
      title: "Piano Basics",
      instructor: "Clara Evans",
      lessons: 12,
      duration: "4h 0m",
      students: 180,
      rating: 4.7,
      price: 49.99,
      category: "Music",
      image: defaultImageBase64
    },
    {
      id: 25,
      title: "Music Theory 101",
      instructor: "Dr. Henry Brooks",
      lessons: 8,
      duration: "2h 30m",
      students: 150,
      rating: 4.6,
      price: 39.99,
      category: "Music",
      image: defaultImageBase64
    },
    {
      id: 26,
      title: "Music Production with Ableton Live",
      instructor: "Alex Reed",
      lessons: 15,
      duration: "5h 0m",
      students: 220,
      rating: 4.8,
      price: 79.99,
      category: "Music",
      image: defaultImageBase64
    },
    {
      id: 27,
      title: "Singing Techniques for Beginners",
      instructor: "Mia Lopez",
      lessons: 9,
      duration: "3h 15m",
      students: 170,
      rating: 4.5,
      price: 49.99,
      category: "Music",
      image: defaultImageBase64
    },
    {
      "id": 28,
      "title": "JavaScript for Beginners",
      "instructor": "Peter Adams",
      "lessons": 10,
      "duration": "3h 30m",
      "students": 230,
      "rating": 4.6,
      "price": 49.99,
      "category": "Programming",
      "image": "defaultImageBase64"
    },
    {
      "id": 29,
      "title": "Advanced UI/UX Prototyping",
      "instructor": "Kelly White",
      "lessons": 12,
      "duration": "4h 0m",
      "students": 160,
      "rating": 4.7,
      "price": 59.99,
      "category": "Design",
      "image": "defaultImageBase64"
    },
    {
      "id": 30,
      "title": "Google Ads Mastery",
      "instructor": "Tom Carter",
      "lessons": 9,
      "duration": "3h 0m",
      "students": 290,
      "rating": 4.8,
      "price": 69.99,
      "category": "Marketing",
      "image": "defaultImageBase64"
    },
    {
      "id": 31,
      "title": "Deep Learning Fundamentals",
      "instructor": "Dr. Susan Park",
      "lessons": 14,
      "duration": "5h 15m",
      "students": 340,
      "rating": 4.9,
      "price": 89.99,
      "category": "Data Science",
      "image": "defaultImageBase64"
    },
    {
      "id": 32,
      "title": "Wildlife Photography Basics",
      "instructor": "Greg Stone",
      "lessons": 8,
      "duration": "2h 45m",
      "students": 140,
      "rating": 4.5,
      "price": 39.99,
      "category": "Photography",
      "image": "defaultImageBase64"
    },
    {
      "id": 33,
      "title": "Pilates for Core Strength",
      "instructor": "Nina Foster",
      "lessons": 10,
      "duration": "3h 0m",
      "students": 210,
      "rating": 4.6,
      "price": 49.99,
      "category": "Health & Fitness",
      "image": "defaultImageBase64"
    },
    {
      "id": 34,
      "title": "Drumming Essentials",
      "instructor": "Luke Harper",
      "lessons": 11,
      "duration": "3h 45m",
      "students": 190,
      "rating": 4.7,
      "price": 59.99,
      "category": "Music",
      "image": "defaultImageBase64"
    },
    {
      "id": 35,
      "title": "CSS Mastery",
      "instructor": "Olivia Bennett",
      "lessons": 9,
      "duration": "3h 15m",
      "students": 200,
      "rating": 4.6,
      "price": 49.99,
      "category": "Programming",
      "image": "defaultImageBase64"
    },
    {
      "id": 36,
      "title": "Graphic Design with Canva",
      "instructor": "Emma Phillips",
      "lessons": 7,
      "duration": "2h 0m",
      "students": 175,
      "rating": 4.4,
      "price": 29.99,
      "category": "Design",
      "image": "defaultImageBase64"
    },
    {
      "id": 37,
      "title": "Affiliate Marketing Strategies",
      "instructor": "Daniel Moore",
      "lessons": 10,
      "duration": "3h 30m",
      "students": 260,
      "rating": 4.7,
      "price": 59.99,
      "category": "Marketing",
      "image": "defaultImageBase64"
    },
    {
      "id": 38,
      "title": "R Programming for Data Science",
      "instructor": "Dr. Ethan Wright",
      "lessons": 12,
      "duration": "4h 30m",
      "students": 310,
      "rating": 4.8,
      "price": 79.99,
      "category": "Data Science",
      "image": "defaultImageBase64"
    },
    {
      "id": 39,
      "title": "Black and White Photography",
      "instructor": "Sophie Turner",
      "lessons": 9,
      "duration": "3h 0m",
      "students": 130,
      "rating": 4.6,
      "price": 49.99,
      "category": "Photography",
      "image": "defaultImageBase64"
    },
    {
      "id": 40,
      "title": "Cardio Kickboxing Basics",
      "instructor": "Mike Lopez",
      "lessons": 8,
      "duration": "2h 30m",
      "students": 180,
      "rating": 4.5,
      "price": 39.99,
      "category": "Health & Fitness",
      "image": "defaultImageBase64"
    },
    {
      "id": 41,
      "title": "Ukulele for Beginners",
      "instructor": "Hannah Kim",
      "lessons": 7,
      "duration": "2h 15m",
      "students": 160,
      "rating": 4.4,
      "price": 29.99,
      "category": "Music",
      "image": "defaultImageBase64"
    },
    {
      "id": 42,
      "title": "Node.js Essentials",
      "instructor": "Chris Young",
      "lessons": 11,
      "duration": "4h 0m",
      "students": 240,
      "rating": 4.7,
      "price": 59.99,
      "category": "Programming",
      "image": "defaultImageBase64"
    },
    {
      "id": 43,
      "title": "Illustration Fundamentals",
      "instructor": "Liam Foster",
      "lessons": 10,
      "duration": "3h 30m",
      "students": 150,
      "rating": 4.6,
      "price": 49.99,
      "category": "Design",
      "image": "defaultImageBase64"
    },
    {
      "id": 44,
      "title": "Brand Storytelling",
      "instructor": "Julia Hayes",
      "lessons": 8,
      "duration": "2h 45m",
      "students": 220,
      "rating": 4.5,
      "price": 49.99,
      "category": "Marketing",
      "image": "defaultImageBase64"
    },
    {
      "id": 45,
      "title": "SQL for Data Analysis",
      "instructor": "Dr. Alice Chen",
      "lessons": 10,
      "duration": "3h 45m",
      "students": 280,
      "rating": 4.8,
      "price": 69.99,
      "category": "Data Science",
      "image": "defaultImageBase64"
    },
    {
      "id": 46,
      "title": "Food Photography Basics",
      "instructor": "Rachel Lee",
      "lessons": 9,
      "duration": "3h 15m",
      "students": 170,
      "rating": 4.7,
      "price": 59.99,
      "category": "Photography",
      "image": "defaultImageBase64"
    },
    {
      "id": 47,
      "title": "Stretching for Flexibility",
      "instructor": "Grace Evans",
      "lessons": 7,
      "duration": "2h 0m",
      "students": 190,
      "rating": 4.6,
      "price": 29.99,
      "category": "Health & Fitness",
      "image": "defaultImageBase64"
    },
    {
      "id": 48,
      "title": "Harmonica Basics",
      "instructor": "Sam Carter",
      "lessons": 8,
      "duration": "2h 30m",
      "students": 140,
      "rating": 4.5,
      "price": 39.99,
      "category": "Music",
      "image": "defaultImageBase64"
    },
    {
      "id": 49,
      "title": "TypeScript Fundamentals",
      "instructor": "Mark Davis",
      "lessons": 10,
      "duration": "3h 30m",
      "students": 210,
      "rating": 4.7,
      "price": 59.99,
      "category": "Programming",
      "image": "defaultImageBase64"
    },
    {
      "id": 50,
      "title": "Motion Graphics with After Effects",
      "instructor": "Zoe Parker",
      "lessons": 12,
      "duration": "4h 15m",
      "students": 180,
      "rating": 4.8,
      "price": 69.99,
      "category": "Design",
      "image": "defaultImageBase64"
    },
    {
      "id": 51,
      "title": "Influencer Marketing 101",
      "instructor": "Brian Scott",
      "lessons": 9,
      "duration": "3h 0m",
      "students": 250,
      "rating": 4.6,
      "price": 49.99,
      "category": "Marketing",
      "image": "defaultImageBase64"
    },
    {
      "id": 52,
      "title": "Big Data with Hadoop",
      "instructor": "Dr. Kevin Liu",
      "lessons": 14,
      "duration": "5h 0m",
      "students": 320,
      "rating": 4.9,
      "price": 89.99,
      "category": "Data Science",
      "image": "defaultImageBase64"
    },
    {
      "id": 53,
      "title": "Aerial Photography with Drones",
      "instructor": "James Carter",
      "lessons": 10,
      "duration": "3h 30m",
      "students": 160,
      "rating": 4.7,
      "price": 59.99,
      "category": "Photography",
      "image": "defaultImageBase64"
    },
    {
      "id": 54,
      "title": "Bodyweight Fitness Basics",
      "instructor": "Ella Brooks",
      "lessons": 8,
      "duration": "2h 45m",
      "students": 200,
      "rating": 4.6,
      "price": 39.99,
      "category": "Health & Fitness",
      "image": "defaultImageBase64"
    },
    {
      "id": 55,
      "title": "Bass Guitar Fundamentals",
      "instructor": "Ryan Kim",
      "lessons": 10,
      "duration": "3h 15m",
      "students": 170,
      "rating": 4.5,
      "price": 49.99,
      "category": "Music",
      "image": "defaultImageBase64"
    },
    { 
      "id": 56,
      "title": "HTML5 and CSS3 Basics",
      "instructor": "Sophia Rivera",
      "lessons": 9,
      "duration": "3h 0m",
      "students": 220,
      "rating": 4.6,
      "price": 49.99,
      "category": "Programming",
      "image": "defaultImageBase64"
    },
    {
      "id": 57,
      "title": "Logo Design Essentials",
      "instructor": "Noah Phillips",
      "lessons": 8,
      "duration": "2h 30m",
      "students": 140,
      "rating": 4.5,
      "price": 39.99,
      "category": "Design",
      "image": "defaultImageBase64"
    },
    {
      "id": 58,
      "title": "E-commerce Marketing",
      "instructor": "Lauren Baker",
      "lessons": 11,
      "duration": "4h 0m",
      "students": 270,
      "rating": 4.7,
      "price": 69.99,
      "category": "Marketing",
      "image": "defaultImageBase64"
    },
    {
      "id": 59,
      "title": "Natural Language Processing Intro",
      "instructor": "Dr. Priya Sharma",
      "lessons": 13,
      "duration": "5h 0m",
      "students": 300,
      "rating": 4.8,
      "price": 79.99,
      "category": "Data Science",
      "image": "defaultImageBase64"
    },
    {
      "id": 60,
      "title": "Night Photography Techniques",
      "instructor": "Ethan Gray",
      "lessons": 9,
      "duration": "3h 15m",
      "students": 150,
      "rating": 4.6,
      "price": 49.99,
      "category": "Photography",
      "image": "defaultImageBase64"
    },
    {
      "id": 61,
      "title": "Zumba Fitness Fun",
      "instructor": "Maria Ortiz",
      "lessons": 10,
      "duration": "3h 0m",
      "students": 230,
      "rating": 4.7,
      "price": 49.99,
      "category": "Health & Fitness",
      "image": "defaultImageBase64"
    },
    {
      "id": 62,
      "title": "Violin for Beginners",
      "instructor": "Isabella Chen",
      "lessons": 12,
      "duration": "4h 0m",
      "students": 180,
      "rating": 4.6,
      "price": 59.99,
      "category": "Music",
      "image": "defaultImageBase64"
    },
    {
      "id": 63,
      "title": "C# Programming Basics",
      "instructor": "Lucas Hayes",
      "lessons": 10,
      "duration": "3h 45m",
      "students": 200,
      "rating": 4.7,
      "price": 59.99,
      "category": "Programming",
      "image": "defaultImageBase64"
    },
    {
      "id": 64,
      "title": "Web Design with Figma",
      "instructor": "Ava Nguyen",
      "lessons": 9,
      "duration": "3h 0m",
      "students": 160,
      "rating": 4.6,
      "price": 49.99,
      "category": "Design",
      "image": "defaultImageBase64"
    },
    {
      "id": 65,
      "title": "Video Marketing Strategies",
      "instructor": "Oliver Reed",
      "lessons": 11,
      "duration": "4h 15m",
      "students": 240,
      "rating": 4.8,
      "price": 69.99,
      "category": "Marketing",
      "image": "defaultImageBase64"
    },
    {
      "id": 66,
      "title": "Excel for Data Analysis",
      "instructor": "Dr. Thomas Bell",
      "lessons": 8,
      "duration": "2h 45m",
      "students": 290,
      "rating": 4.7,
      "price": 49.99,
      "category": "Data Science",
      "image": "defaultImageBase64"
    },
    {
      "id": 67,
      "title": "Macro Photography Mastery",
      "instructor": "Claire Adams",
      "lessons": 10,
      "duration": "3h 30m",
      "students": 140,
      "rating": 4.5,
      "price": 59.99,
      "category": "Photography",
      "image": "defaultImageBase64"
    },
    {
      "id": 68,
      "title": "Kettlebell Training Basics",
      "instructor": "Josh Carter",
      "lessons": 9,
      "duration": "2h 30m",
      "students": 180,
      "rating": 4.6,
      "price": 39.99,
      "category": "Health & Fitness",
      "image": "defaultImageBase64"
    },
    {
      "id": 69,
      "title": "Saxophone Fundamentals",
      "instructor": "Ella Foster",
      "lessons": 10,
      "duration": "3h 15m",
      "students": 150,
      "rating": 4.5,
      "price": 49.99,
      "category": "Music",
      "image": "defaultImageBase64"
    },
    {
      "id": 70,
      "title": "PHP for Web Development",
      "instructor": "Nathan Lee",
      "lessons": 11,
      "duration": "4h 0m",
      "students": 210,
      "rating": 4.7,
      "price": 59.99,
      "category": "Programming",
      "image": "defaultImageBase64"
    },
    {
      "id": 71,
      "title": "Typography Design",
      "instructor": "Mia Roberts",
      "lessons": 8,
      "duration": "2h 45m",
      "students": 130,
      "rating": 4.5,
      "price": 39.99,
      "category": "Design",
      "image": "defaultImageBase64"
    },
    {
      "id": 72,
      "title": "PPC Advertising Basics",
      "instructor": "Henry Brooks",
      "lessons": 10,
      "duration": "3h 30m",
      "students": 260,
      "rating": 4.6,
      "price": 59.99,
      "category": "Marketing",
      "image": "defaultImageBase64"
    },
    {
      "id": 73,
      "title": "Time Series Analysis",
      "instructor": "Dr. Rachel Kim",
      "lessons": 12,
      "duration": "4h 30m",
      "students": 280,
      "rating": 4.8,
      "price": 79.99,
      "category": "Data Science",
      "image": "defaultImageBase64"
    },
    {
      "id": 74,
      "title": "Travel Photography Tips",
      "instructor": "Liam Scott",
      "lessons": 9,
      "duration": "3h 0m",
      "students": 170,
      "rating": 4.7,
      "price": 49.99,
      "category": "Photography",
      "image": "defaultImageBase64"
    },
    {
      "id": 75,
      "title": "Boxing Basics for Fitness",
      "instructor": "Tyler Evans",
      "lessons": 10,
      "duration": "3h 15m",
      "students": 200,
      "rating": 4.6,
      "price": 49.99,
      "category": "Health & Fitness",
      "image": "defaultImageBase64"
    },
    {
      "id": 76,
      "title": "Flute for Beginners",
      "instructor": "Sophie Lee",
      "lessons": 8,
      "duration": "2h 30m",
      "students": 140,
      "rating": 4.5,
      "price": 39.99,
      "category": "Music",
      "image": "defaultImageBase64"
    },
    {
      "id": 77,
      "title": "Ruby on Rails Basics",
      "instructor": "Alex Turner",
      "lessons": 11,
      "duration": "4h 0m",
      "students": 230,
      "rating": 4.7,
      "price": 59.99,
      "category": "Programming",
      "image": "defaultImageBase64"
    },
    {
      "id": 78,
      "title": "Packaging Design 101",
      "instructor": "Emma Davis",
      "lessons": 9,
      "duration": "3h 0m",
      "students": 150,
      "rating": 4.6,
      "price": 49.99,
      "category": "Design",
      "image": "defaultImageBase64"
    },
    {
      "id": 79,
      "title": "Social Media Analytics",
      "instructor": "Chris Patel",
      "lessons": 10,
      "duration": "3h 30m",
      "students": 250,
      "rating": 4.8,
      "price": 69.99,
      "category": "Marketing",
      "image": "defaultImageBase64"
    },
    {
      "id": 80,
      "title": "Data Engineering Basics",
      "instructor": "Dr. John Yang",
      "lessons": 13,
      "duration": "5h 0m",
      "students": 310,
      "rating": 4.9,
      "price": 89.99,
      "category": "Data Science",
      "image": "defaultImageBase64"
    },
    {
      "id": 81,
      "title": "Sports Photography Essentials",
      "instructor": "Mark Wilson",
      "lessons": 10,
      "duration": "3h 15m",
      "students": 160,
      "rating": 4.7,
      "price": 59.99,
      "category": "Photography",
      "image": "defaultImageBase64"
    },
    {
      "id": 82,
      "title": "Tai Chi for Beginners",
      "instructor": "Lina Chen",
      "lessons": 8,
      "duration": "2h 30m",
      "students": 180,
      "rating": 4.6,
      "price": 39.99,
      "category": "Health & Fitness",
      "image": "defaultImageBase64"
    },
    {
      "id": 83,
      "title": "Songwriting Basics",
      "instructor": "Julia Carter",
      "lessons": 9,
      "duration": "3h 0m",
      "students": 170,
      "rating": 4.5,
      "price": 49.99,
      "category": "Music",
      "image": "defaultImageBase64"
    },
    {
      "id": 84,
      "title": "Go Programming Fundamentals",
      "instructor": "David Kim",
      "lessons": 10,
      "duration": "3h 45m",
      "students": 200,
      "rating": 4.7,
      "price": 59.99,
      "category": "Programming",
      "image": "defaultImageBase64"
    },
    {
      "id": 85,
      "title": "Interior Design Basics",
      "instructor": "Sara Evans",
      "lessons": 11,
      "duration": "4h 0m",
      "students": 140,
      "rating": 4.6,
      "price": 59.99,
      "category": "Design",
      "image": "defaultImageBase64"
    },
    {
      "id": 86,
      "title": "SEO Advanced Techniques",
      "instructor": "Paul Harris",
      "lessons": 12,
      "duration": "4h 30m",
      "students": 270,
      "rating": 4.8,
      "price": 79.99,
      "category": "Marketing",
      "image": "defaultImageBase64"
    },
    {
      "id": 87,
      "title": "Predictive Analytics with Python",
      "instructor": "Dr. Emily Chen",
      "lessons": 14,
      "duration": "5h 15m",
      "students": 330,
      "rating": 4.9,
      "price": 89.99,
      "category": "Data Science",
      "image": "defaultImageBase64"
    },
    {
      "id": 88,
      "title": "Wedding Photography Tips",
      "instructor": "Anna Parker",
      "lessons": 10,
      "duration": "3h 30m",
      "students": 150,
      "rating": 4.7,
      "price": 59.99,
      "category": "Photography",
      "image": "defaultImageBase64"
    },
    {
      "id": 89,
      "title": "Running for Endurance",
      "instructor": "Jake Foster",
      "lessons": 9,
      "duration": "2h 45m",
      "students": 190,
      "rating": 4.6,
      "price": 39.99,
      "category": "Health & Fitness",
      "image": "defaultImageBase64"
    },
    {
      "id": 90,
      "title": "Electronic Music Production",
      "instructor": "Max Reed",
      "lessons": 12,
      "duration": "4h 15m",
      "students": 200,
      "rating": 4.8,
      "price": 69.99,
      "category": "Music",
      "image": "defaultImageBase64"
    },
    {
      "id": 91,
      "title": "Swift for iOS Development",
      "instructor": "Tom Nguyen",
      "lessons": 11,
      "duration": "4h 0m",
      "students": 220,
      "rating": 4.7,
      "price": 59.99,
      "category": "Programming",
      "image": "defaultImageBase64"
    },
    {
      "id": 92,
      "title": "Fashion Design Basics",
      "instructor": "Lily Adams",
      "lessons": 10,
      "duration": "3h 30m",
      "students": 130,
      "rating": 4.5,
      "price": 49.99,
      "category": "Design",
      "image": "defaultImageBase64"
    },
    {
      "id": 93,
      "title": "Content Creation for YouTube",
      "instructor": "Ryan Patel",
      "lessons": 9,
      "duration": "3h 0m",
      "students": 260,
      "rating": 4.6,
      "price": 59.99,
      "category": "Marketing",
      "image": "defaultImageBase64"
    },
    {
      "id": 94,
      "title": "Blockchain Data Analysis",
      "instructor": "Dr. Michael Wu",
      "lessons": 13,
      "duration": "5h 0m",
      "students": 300,
      "rating": 4.8,
      "price": 89.99,
      "category": "Data Science",
      "image": "defaultImageBase64"
    },
    {
      "id": 95,
      "title": "Pet Photography Techniques",
      "instructor": "Kate Miller",
      "lessons": 8,
      "duration": "2h 45m",
      "students": 140,
      "rating": 4.6,
      "price": 39.99,
      "category": "Photography",
      "image": "defaultImageBase64"
    },
    {
      "id": 96,
      "title": "Cycling for Fitness",
      "instructor": "Ben Carter",
      "lessons": 10,
      "duration": "3h 15m",
      "students": 200,
      "rating": 4.7,
      "price": 49.99,
      "category": "Health & Fitness",
      "image": "defaultImageBase64"
    },
    {
      "id": 97,
      "title": "Jazz Guitar Basics",
      "instructor": "Leo Brooks",
      "lessons": 11,
      "duration": "3h 45m",
      "students": 180,
      "rating": 4.6,
      "price": 59.99,
      "category": "Music",
      "image": "defaultImageBase64"
    },
    {
      "id": 98,
      "title": "Kotlin for Android Development",
      "instructor": "Sara Kim",
      "lessons": 12,
      "duration": "4h 15m",
      "students": 230,
      "rating": 4.8,
      "price": 69.99,
      "category": "Programming",
      "image": "defaultImageBase64"
    },
    {
      "id": 99,
      "title": "Product Design Essentials",
      "instructor": "James Lee",
      "lessons": 10,
      "duration": "3h 30m",
      "students": 150,
      "rating": 4.7,
      "price": 59.99,
      "category": "Design",
      "image": "defaultImageBase64"
    },
    {
      "id": 100,
      "title": "Email Automation Strategies",
      "instructor": "Nina Patel",
      "lessons": 9,
      "duration": "3h 0m",
      "students": 240,
      "rating": 4.6,
      "price": 49.99,
      "category": "Marketing",
      "image": "defaultImageBase64"
    }
  ]
};

// Export the data
module.exports = { coursesData };
